create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  customer_address text not null,
  customer_notes text,
  items jsonb not null,
  total_amount numeric(10,2) not null,
  currency text not null default 'EUR',
  order_status text not null default 'new' check (order_status in ('new', 'preparing', 'out_for_delivery', 'delivered', 'cancelled')),
  delivery_partner text,
  estimated_minutes integer,
  tracking_note text,
  delivered_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.orders
  add column if not exists order_status text not null default 'new';

alter table public.orders
  add column if not exists delivery_partner text;

alter table public.orders
  add column if not exists estimated_minutes integer;

alter table public.orders
  add column if not exists tracking_note text;

alter table public.orders
  add column if not exists delivered_at timestamptz;

alter table public.orders
  add column if not exists updated_at timestamptz;

update public.orders
set order_status = 'new'
where order_status is null;

alter table public.orders
  alter column order_status set default 'new';

alter table public.orders
  alter column order_status set not null;

alter table public.orders
  drop constraint if exists orders_order_status_check;

alter table public.orders
  add constraint orders_order_status_check
  check (order_status in ('new', 'preparing', 'out_for_delivery', 'delivered', 'cancelled'));

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (order_status);

alter table public.orders enable row level security;

grant usage on schema public to anon, authenticated;
grant insert, select, update on public.orders to anon, authenticated;
grant usage, select on sequence public.orders_id_seq to anon, authenticated;

do $$
declare
  policy_name text;
begin
  for policy_name in
    select polname
    from pg_policy
    where polrelid = 'public.orders'::regclass
  loop
    execute format('drop policy if exists %I on public.orders', policy_name);
  end loop;
end
$$;

create policy "orders_insert_public"
on public.orders
for insert
to public
with check (true);

create policy "orders_select_authenticated"
on public.orders
for select
to authenticated
using (true);

create policy "orders_select_anon"
on public.orders
for select
to anon
using (true);

create policy "orders_update_public"
on public.orders
for update
to public
using (true)
with check (true);
